name: CI

on:
  push:
    paths:
    - '**.py'
    - '.github/workflows/ci.yml'
    - '**.rst'

jobs:
  lint-code:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install setuptools
        run: sudo apt-get install python3-setuptools

      - name: Install black
        run: pip3 install black flake8

      - name: Lint - Black fake_package
        run: python3 -m black fake_package/

      - name: Lint - Black tests
        run: python3 -m black tests/

      - name: Lint - flake8
        run: python3 -m flake8

  run-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install setuptools
        run: sudo apt-get install python3-setuptools

      - name: Upgrade pip
        run: pip3 install -U pip

      - name: Get pip cache dir
        id: pip-cache
        run: |
          echo "::set-output name=dir::$(pip3 cache dir)"

      - name: cache python modules
        uses: actions/cache@v2
        with:
          path: ${{ steps.pip-cache.outputs.dir }}
          key: ${{ runner.os }}-pip-tests-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-tests-

      - name: Install dependencies
        run: pip3 install -r requirements.txt

      - name: Run tests
        run: python3 -m unittest

  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install Python with setuptools
        run: sudo apt-get install python3-setuptools

      - name: "Install Sphinx"
        run: pip3 install sphinx sphinx-rtd-theme

      - name: "Build Sphinx Doc"
        run: export PYTHONPATH=.. && cd docs && make html

      - name: "Deploy Github Pages"
        uses: JamesIves/github-pages-deploy-action@4.1.7
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages     
          FOLDER: docs/build/html/  
